# Generated by Django 4.2.2 on 2023-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('shipment_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_time', models.DateField()),
                ('delivery_status', models.TextField()),
            ],
        ),
    ]
