# Generated by Django 4.2.3 on 2023-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ship',
            field=models.ManyToManyField(to='order.order'),
        ),
    ]
