# Generated by Django 4.2.2 on 2023-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('payment_options', models.CharField(max_length=16)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
