# Generated by Django 4.2.2 on 2023-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_discount_alter_cart_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number_of_products',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_options',
            field=models.CharField(max_length=32),
        ),
    ]
