# Generated by Django 4.2.2 on 2023-06-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_number_of_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
