# Generated by Django 4.2.2 on 2023-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('products', models.TextField()),
                ('customer', models.CharField(max_length=100)),
            ],
        ),
    ]
